name: Build Instafader

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build executable
      run: pyinstaller "src/main.py" --onefile --name "Instafader" 
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Instafader
        path: dist\Instafader.exe
